# Generated by Django 5.2.10 on 2026-01-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_tweetanalysis_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_data', models.JSONField()),
                ('hour_data', models.JSONField(blank=True, null=True)),
                ('like_weighted_sentiment', models.JSONField(blank=True, null=True)),
                ('top_words_positive', models.JSONField(blank=True, null=True)),
                ('top_words_negative', models.JSONField(blank=True, null=True)),
                ('total_comments_analyzed', models.IntegerField()),
                ('filtered_spam_count', models.IntegerField(default=0)),
                ('filtered_language_count', models.IntegerField(default=0)),
                ('filtered_short_count', models.IntegerField(default=0)),
                ('fetched_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_model', models.CharField(default='LOGREG', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Analysis',
                'verbose_name_plural': 'YouTube Analyses',
                'ordering': ['-fetched_date'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('is_reply', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'YouTube Comment',
                'verbose_name_plural': 'YouTube Comments',
                'ordering': ['-likes', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=11, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField()),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tweetanalysis',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
        migrations.AddField(
            model_name='youtubecomment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.youtubevideo'),
        ),
        migrations.AddField(
            model_name='youtubeanalysis',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='app.youtubevideo'),
        ),
        migrations.DeleteModel(
            name='TweetAnalysis',
        ),
    ]
