# Generated by Django 5.2.10 on 2026-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_youtubeanalysis_youtubecomment_youtubevideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeanalysis',
            name='analysis_meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
