# Generated by Django 5.2.16 on 2026-08-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_analysisjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecomment',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True when the entropy gate withheld a label as too uncertain to trust.'),
        ),
    ]
